server:
  port: 8080

grpc:
  client:
    extractionResults:
      address: static://localhost:9090
      negotiationType: plaintext
    usersInfo:
      address: static://localhost:9091
      negotiationType: plaintext
